// ReturnToKin — Design token constants
// Mirrors globals.css for use in JS/TS components

export const theme = {
  colors: {
    navy: '#071E3D',
    navyDark: '#04152D',
    navyLight: '#0F2B4F',
    teal: '#0B7B8A',
    tealLight: '#E8F4F6',
    tealDark: '#086070',
    missing: '#D97706',
    success: '#059669',
    warning: '#D97706',
    error: '#DC2626',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    bg: '#F8FAFC',
    surface: '#FFFFFF',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
  },
  breakpoints: {
    sm: 640,
    md: 768,
    lg: 1024,
    xl: 1280,
  },
} as const;

// Fictional demo cases for development
export const demoCases = [
  {
    id: 'RTK-26-A7F3',
    name: 'Sofia Martin',
    age: 22,
    nationality: 'Spain',
    lastSeen: 'Barcelona, Spain',
    date: '3 Mar 2026',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen near the Gothic Quarter. Wearing a light jacket and carrying a backpack.',
  },
  {
    id: 'RTK-26-B8D2',
    name: 'Daniel Kim',
    age: 28,
    nationality: 'South Korea',
    lastSeen: 'Seoul, South Korea',
    date: '15 May 2024',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen leaving his workplace in Gangnam District.',
  },
  {
    id: 'RTK-26-C9E1',
    name: 'Aisha Rahman',
    age: 31,
    nationality: 'Bangladesh',
    lastSeen: 'Dhaka, Bangladesh',
    date: '22 Feb 2026',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen near Uttara sector 12. Wearing a green dupatta.',
  },
  {
    id: 'RTK-26-D0F4',
    name: 'Lucas Moreau',
    age: 45,
    nationality: 'France',
    lastSeen: 'Marseille, France',
    date: '8 Apr 2026',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen near the Old Port area.',
  },
  {
    id: 'RTK-26-E1G5',
    name: 'Chiamaka N.',
    age: 24,
    nationality: 'Nigeria',
    lastSeen: 'Lagos, Nigeria',
    date: '11 Jan 2026',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen at Yaba bus stop. Wearing a blue dress.',
  },
  {
    id: 'RTK-26-F2H6',
    name: 'Maria Silva',
    age: 36,
    nationality: 'Brazil',
    lastSeen: 'São Paulo, Brazil',
    date: '30 Jun 2026',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen near Avenida Paulista.',
  },
  {
    id: 'RTK-26-G3I7',
    name: 'Ahmed A.',
    age: 27,
    nationality: 'Jordan',
    lastSeen: 'Istanbul, Türkiye',
    date: '14 Aug 2026',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen in the Fatih district. Wearing a dark grey jacket.',
  },
  {
    id: 'RTK-26-H4J8',
    name: 'Sergey Ivanov',
    age: 52,
    nationality: 'Ukraine',
    lastSeen: 'Kyiv, Ukraine',
    date: '3 Sep 2026',
    status: 'MISSING · VERIFIED',
    image: null,
    description: 'Last seen near the central train station.',
  },
];

// Demo stats (placeholder)
export const demoStats = {
  cases: null,
  countries: null,
  partners: null,
  reconnections: null,
} as const;